---
#---------------------------------------
# 1. docker-compose -p comp3123-assign2 -f docker-compose.yml up -d
#   -- This command will start containers in detached mode without rebuilding the images (if they already exist)
#
# 2. docker-compose -p comp3123-assign2 -f docker-compose.yml up -d --build
#   -- This command forces the image to rebuild before starting the container. Run after changes.
#---------------------------------------

version: "3.9"

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: ./DockerFile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://backend:5000
    networks:
      - my-network

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: ./DockerFile
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      DB_URL: mongodb://mongodb:27017/mydatabase
      TOKEN: /run/secrets/token
    networks:
      - my-network

  mongodb:
    image: mongo:latest
    container_name: mongodb-comp3123 # must be unique
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=mydatabase
    volumes: # persistent storage
      - ./data:/data/db
    #restart: unless-stopped    # keep trying to start until it works
    #command: mongod -auth      # enforces authorization
    networks:
      - my-network

  mongo-express:
    image: mongo-express:latest
    ports:
      - "8083:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
    container_name: mongo-express-comp3123
    depends_on:
      - mongodb
    networks:
      - my-network

secrets:
  token:
    file: ./token.txt

volumes:
  data:

networks:
  my-network:
    driver: bridge
